export const EDIT_TILE = 'EDIT_TILE';
export const SEARCH = 'SEARCH';
export const TILES_LOAD_INIT = 'TILES_LOAD_INIT';
export const SET_SELECTED_TILE_ID = 'SET_SELECTED_TILE_ID';
export const TILES_FETCH_SUCCEEDED = 'TILES_FETCH_SUCCEEDED';
export const TILE_EDIT_SUCCEEDED = 'TILE_EDIT_SUCCEEDED';
export const SET_LOADER_STATE = 'SET_LOADER_STATE';
